const CATALOGUE = [
  {id:'peanutgb',name:'Peanut-GB — Game Boy',file:'peanutgb.nwa',url:'https://codeberg.org/Yaya-Cout/peanutgb/releases/download/v1.2.2/peanutgb.nwa',roms:['.gb']},
  {id:'peanutgbc',name:'Peanut-GBC — Game Boy Color',file:'peanutgbc.nwa',url:'https://codeberg.org/Yaya-Cout/peanutgbc/releases/download/v1.1.1/peanutgbc.nwa',roms:['.gbc','.gb']},
  {id:'nofrendo',name:'Nofrendo — NES',file:'nofrendo.nwa',url:'https://codeberg.org/Yaya-Cout/nofrendo/releases/download/v1.2.3/nofrendo.nwa',roms:['.nes']}
];
const $=id=>document.getElementById(id), DB='numworks-android-files', STORE='files';
let apps=[], deferredInstall=null, toastTimer;
let connectedCalculator=null, calculatorInfos=null, operationBusy=false;
const dbReady=new Promise((resolve,reject)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});
async function dbSet(key,value){const db=await dbReady;return new Promise((resolve,reject)=>{const t=db.transaction(STORE,'readwrite');t.objectStore(STORE).put(value,key);t.oncomplete=resolve;t.onerror=()=>reject(t.error)})}
async function dbGet(key){const db=await dbReady;return new Promise((resolve,reject)=>{const r=db.transaction(STORE).objectStore(STORE).get(key);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function dbDelete(key){const db=await dbReady;return new Promise((resolve,reject)=>{const t=db.transaction(STORE,'readwrite');t.objectStore(STORE).delete(key);t.oncomplete=resolve;t.onerror=()=>reject(t.error)})}
function say(message){const el=$('toast');el.textContent=message;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2800);const line=document.createElement('div');line.className='logline';line.textContent=`${new Date().toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})}  ${message}`;$('log').prepend(line)}
function size(n){if(n<1024)return `${n} o`;if(n<1048576)return `${(n/1024).toFixed(1)} Ko`;return `${(n/1048576).toFixed(2)} Mo`}
function id(){return crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random()}`}
async function assertNwaElf(blob,name){const h=new Uint8Array(await blob.slice(0,20).arrayBuffer()),label=name||'application.nwa';if(h.length<20||h[0]!==0x7f||h[1]!==0x45||h[2]!==0x4c||h[3]!==0x46)throw Error(`« ${label} » n’est pas un vrai fichier .nwa NumWorks (signature ELF absente). Retélécharge le fichier .nwa, pas la page HTML ni une archive ZIP.`);if(h[4]!==1||h[5]!==1||(h[18]|h[19]<<8)!==40)throw Error(`« ${label} » est un fichier ELF, mais pas une application NumWorks ARM compatible.`)}
function saveMeta(){localStorage.setItem('numworks-apps',JSON.stringify(apps))}
async function restore(){try{apps=JSON.parse(localStorage.getItem('numworks-apps')||'[]');const valid=[];for(const a of apps){a.nwaBlob=await dbGet(a.nwaKey);a.dataBlob=a.dataKey?await dbGet(a.dataKey):null;if(a.nwaBlob||a.url)valid.push(a)}apps=valid}catch{apps=[]}render()}
function render(){const list=$('appList');list.replaceChildren();if(!apps.length){const empty=document.createElement('div');empty.className='empty';empty.textContent='Votre liste est vide. Ajoutez une appli pour commencer.';list.append(empty)}
  apps.forEach((a,i)=>{const card=document.createElement('article');card.className='app-card';const title=document.createElement('div');title.className='app-title';title.textContent=a.dataName?`${a.name} — ${a.dataName.replace(/\.[^.]+$/,'')}`:a.name;card.append(title);const meta=document.createElement('div');meta.className='app-meta';meta.textContent=`${a.nwaName||'à télécharger'} · ${size((a.nwaBlob?.size||0)+(a.dataBlob?.size||0))}`;card.append(meta);if(!a.nwaBlob&&a.url){const link=document.createElement('a');link.className='text-button';link.href=a.url;link.target='_blank';link.rel='noopener';link.download=a.nwaName;link.textContent=`Télécharger ${a.nwaName}`;link.style.display='inline-block';link.style.marginTop='8px';card.append(link)}const badges=document.createElement('div');badges.className='badges';if(a.needsRom&&!a.dataBlob){const b=document.createElement('span');b.className='badge warn';b.textContent='ROM requise';badges.append(b)}if(a.dataBlob){const b=document.createElement('span');b.className='badge';b.textContent=a.dataName;badges.append(b)}card.append(badges);const controls=document.createElement('div');controls.className='card-controls';controls.append(button('ROM / données',()=>pickRom(i),'small-button'));controls.append(button('↑',()=>move(i,-1),'small-button'));controls.append(button('↓',()=>move(i,1),'small-button'));controls.append(button('Supprimer',()=>removeApp(i),'small-button remove'));card.append(controls);list.append(card)});
  const total=apps.reduce((n,a)=>n+(a.nwaBlob?.size||0)+(a.dataBlob?.size||0),0);$('summary').textContent=apps.length?`${apps.length} appli${apps.length>1?'s':''} · ${size(total)}`:'Liste vide';$('exportPreset').disabled=!apps.length;$('dryRun').disabled=operationBusy;$('installGroup').disabled=operationBusy;$('connectUsb').disabled=operationBusy;
}
function button(label,fn,cls){const b=document.createElement('button');b.type='button';b.className=cls;b.textContent=label;b.onclick=fn;return b}
async function addFile(file){if(file.name.toLowerCase().endsWith('.nwa')){try{await assertNwaElf(file,file.name)}catch(e){say(e.message);return}}const pending=apps.find(a=>!a.nwaBlob&&a.nwaName.toLowerCase()===file.name.toLowerCase());if(pending){pending.nwaBlob=file;await dbSet(pending.nwaKey,file);saveMeta();render();say(`${file.name} rattaché à ${pending.name}.`);return}const key=id(),suggestion=findCatalogRom(file),a={key,name:file.name.replace(/\.nwa$/i,''),nwaName:file.name,needsRom:false,nwaKey:key,nwaBlob:file,dataBlob:null};await dbSet(key,file);apps.push(a);saveMeta();render();say(`${file.name} ajouté à la liste.${suggestion?` Émulateur conseillé pour une ROM ${suggestion.name}.`:''}`)}
function move(i,d){const j=i+d;if(j<0||j>=apps.length)return;[apps[i],apps[j]]=[apps[j],apps[i]];saveMeta();render()}
async function removeApp(i){const a=apps.splice(i,1)[0];await dbDelete(a.nwaKey);if(a.dataKey)await dbDelete(a.dataKey);saveMeta();render();say(`${a.name} retiré.`)}
async function pickRom(i){const input=document.createElement('input');input.type='file';input.accept='.gb,.gbc,.nes,.ch8,.png,.bin,.txt,*/*';input.onchange=async()=>{const file=input.files[0];if(!file)return;const a=apps[i];if(a.dataKey)await dbDelete(a.dataKey);a.dataKey=id();a.dataBlob=file;a.dataName=file.name;await dbSet(a.dataKey,file);saveMeta();render();say(`Données ${file.name} associées à ${a.name}.`)};input.click()}
function ext(name){return (name.match(/\.[^.]+$/)||[''])[0].toLowerCase()}
function findCatalogRom(file){const e=ext(file.name);return CATALOGUE.find(c=>c.roms.includes(e))}
async function addFromCatalog(entry){const key=id(),a={key,name:entry.name,nwaName:entry.file,needsRom:true,emulator:entry.id,url:entry.url,nwaKey:key,nwaBlob:null,dataBlob:null};apps.push(a);saveMeta();render();say(`${entry.name} ajouté. Téléchargement du fichier…`);try{const response=await fetch(entry.url);if(!response.ok)throw new Error(`HTTP ${response.status}`);const blob=await response.blob();await assertNwaElf(blob,entry.file);a.nwaBlob=blob;await dbSet(key,blob);saveMeta();render();say(`${entry.file} téléchargé.`)}catch(e){render();say(e.message?.includes('signature ELF')?e.message:`Téléchargement automatique indisponible. Utilisez le lien de téléchargement affiché dans la liste, puis choisissez ${entry.file} avec le bouton fichiers.`)}}

// Petit générateur ZIP sans dépendance : le format de preset est compatible avec le PC.
const crcTable=(()=>{const t=new Uint32Array(256);for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=c&1?0xedb88320^(c>>>1):c>>>1;t[n]=c>>>0}return t})();
function crc32(bytes){let c=0xffffffff;for(const b of bytes)c=crcTable[(c^b)&255]^(c>>>8);return(c^0xffffffff)>>>0}
function put16(v,n){v.push(n&255,(n>>>8)&255)}function put32(v,n){v.push(n&255,(n>>>8)&255,(n>>>16)&255,(n>>>24)&255)}
async function makeZip(entries){const local=[],central=[];let offset=0;for(const e of entries){const name=new TextEncoder().encode(e.name),data=e.data instanceof Uint8Array?e.data:new Uint8Array(await e.data.arrayBuffer()),crc=crc32(data),l=[];put32(l,0x04034b50);put16(l,20);put16(l,0);put16(l,0);put16(l,0);put16(l,0);put32(l,crc);put32(l,data.length);put32(l,data.length);put16(l,name.length);put16(l,0);l.push(...name);local.push(new Uint8Array([...l,...data]));const c=[];put32(c,0x02014b50);put16(c,20);put16(c,20);put16(c,0);put16(c,0);put16(c,0);put16(c,0);put32(c,crc);put32(c,data.length);put32(c,data.length);put16(c,name.length);put16(c,0);put16(c,0);put16(c,0);put16(c,0);put32(c,0);put32(c,offset);c.push(...name);central.push(new Uint8Array(c));offset+=l.length+data.length}const dir=central.reduce((n,b)=>n+b.length,0),end=[];put32(end,0x06054b50);put16(end,0);put16(end,0);put16(end,entries.length);put16(end,entries.length);put32(end,dir);put32(end,offset);put16(end,0);return new Blob([...local,...central.map(x=>x.buffer),new Uint8Array(end)],{type:'application/zip'})}
async function exportPreset(){if(!apps.length)return;try{const manifest={format:'numworks-installateur-preset',version:1,applis:[]},entries=[];for(let i=0;i<apps.length;i++){const a=apps[i];if(!a.nwaBlob){throw new Error(`Le fichier ${a.nwaName} manque. Ajoutez-le depuis le catalogue ou choisissez le fichier .nwa.`)}const nwa=`fichiers/${String(i).padStart(4,'0')}-application.nwa`,data=a.dataBlob?`fichiers/${String(i).padStart(4,'0')}-donnees${ext(a.dataName)||'.bin'}`:null;manifest.applis.push({nom:a.name,emulateur:a.emulator||null,nwa,nom_nwa:a.nwaName,donnees:data,nom_donnees:data?a.dataName:null});entries.push({name:nwa,data:a.nwaBlob});if(data)entries.push({name:data,data:a.dataBlob})}entries.unshift({name:'preset.json',data:new TextEncoder().encode(JSON.stringify(manifest,null,2))});const blob=await makeZip(entries),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='numworks.nwpreset';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);say('Preset exporté.')}catch(e){say(e.message)}}
async function readZip(blob){const b=new Uint8Array(await blob.arrayBuffer()),v=new DataView(b.buffer),decoder=new TextDecoder();let eocd=-1;for(let i=b.length-22;i>=Math.max(0,b.length-65558);i--)if(v.getUint32(i,true)===0x06054b50){eocd=i;break}if(eocd<0)throw Error('Archive ZIP non valide.');const count=v.getUint16(eocd+10,true),dir=v.getUint32(eocd+16,true),files={};let p=dir;for(let i=0;i<count;i++){if(v.getUint32(p,true)!==0x02014b50)throw Error('Entrée ZIP invalide.');const method=v.getUint16(p+10,true),size=v.getUint32(p+20,true),nl=v.getUint16(p+28,true),el=v.getUint16(p+30,true),cl=v.getUint16(p+32,true),local=v.getUint32(p+42,true),name=decoder.decode(b.slice(p+46,p+46+nl));if(name.includes('..')||name.startsWith('/'))throw Error('Chemin invalide dans le preset.');const start=local+30+v.getUint16(local+26,true)+v.getUint16(local+28,true),raw=b.slice(start,start+size);if(method===0)files[name]=raw;else if(method===8){if(!('DecompressionStream'in window))throw Error('Ce navigateur ne sait pas ouvrir ce preset compressé.');files[name]=new Uint8Array(await new Response(new Blob([raw]).stream().pipeThrough(new DecompressionStream('deflate-raw'))).arrayBuffer())}else throw Error('Compression ZIP non prise en charge.');p+=46+nl+el+cl}return files}
async function importPreset(file){try{const files=await readZip(file),manifest=JSON.parse(new TextDecoder().decode(files['preset.json']));if(manifest.format!=='numworks-installateur-preset'||manifest.version!==1||!Array.isArray(manifest.applis)||!manifest.applis.length)throw Error('Format de preset non reconnu ou liste vide.');if(manifest.applis.length>500)throw Error('Le preset dépasse 500 applications.');const next=[];for(const item of manifest.applis){if(!files[item.nwa]||!item.nom_nwa?.toLowerCase().endsWith('.nwa'))throw Error('Un fichier .nwa référencé est absent.');const key=id(),nwa=new Blob([files[item.nwa]]);await assertNwaElf(nwa,item.nom_nwa);await dbSet(key,nwa);let dataBlob=null,dataKey=null;if(item.donnees){if(!files[item.donnees])throw Error('Un fichier de données est absent.');dataKey=id();dataBlob=new Blob([files[item.donnees]]);await dbSet(dataKey,dataBlob)}next.push({key,name:item.nom||item.nom_nwa.replace(/\.nwa$/i,''),nwaName:item.nom_nwa,needsRom:['peanutgb','peanutgbc','nofrendo'].includes(item.emulateur),emulator:item.emulateur||null,nwaKey:key,nwaBlob:nwa,dataKey,dataBlob,dataName:item.nom_donnees||null})}for(const old of apps){await dbDelete(old.nwaKey);if(old.dataKey)await dbDelete(old.dataKey)}apps=next;saveMeta();render();say(`Preset importé : ${apps.length} application(s).`)}catch(e){say(`Import impossible : ${e.message}`)}}

function entriesForInstall(){if(!apps.length)throw Error('Ajoutez au moins une application.');const missing=apps.filter(a=>!a.nwaBlob);if(missing.length)throw Error(`Fichier .nwa manquant : ${missing.map(a=>a.nwaName).join(', ')}`);const withoutData=apps.filter(a=>a.needsRom&&!a.dataBlob);if(withoutData.length)throw Error(`ROM/données requises : ${withoutData.map(a=>a.name).join(', ')}`);const total=apps.reduce((n,a)=>n+a.nwaBlob.size+(a.dataBlob?.size||0),0);if(total>8*1024*1024)throw Error('La sélection dépasse la limite de 8 Mo des applications externes.');return total}
async function makeBundle(){entriesForInstall();const api=window.NwlinkBrowserAPI;if(!api)throw Error('Le moteur d’assemblage n’a pas pu démarrer. Rechargez l’application.');const bundle=new api.Bundle();for(const a of apps){await assertNwaElf(a.nwaBlob,a.nwaName);const nwa=new api.NWA(new Uint8Array(await a.nwaBlob.arrayBuffer()));if(a.dataBlob){/* setExternalData déclenche un assemblage WASM de diagnostic en arrière-plan. L’installation groupe assemble déjà chaque NWA : éviter ce calcul doublé sur mobile. */nwa.externalData=new Uint8Array(await a.dataBlob.arrayBuffer())}bundle.push(nwa)}return bundle}
function setProgress(value,label){$('progressWrap').hidden=false;$('progressBar').style.width=`${Math.max(0,Math.min(100,value*100))}%`;$('progressText').textContent=label}
async function dryRun(){if(operationBusy)return;operationBusy=true;render();$('progressWrap').hidden=false;setProgress(.02,'Assemblage…');try{const bundle=await makeBundle();const image=await bundle.flatBin({flashStart:2415919104,flashLength:8388608,ramStart:536870912,ramLength:262144,trampolineStart:2415984688});setProgress(1,`${size(image.byteLength)} · prêt`);const url=URL.createObjectURL(new Blob([image],{type:'application/octet-stream'})),a=document.createElement('a');a.href=url;a.download='numworks-apps.bin';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);say(`Assemblage réussi : ${size(image.byteLength)} pour ${apps.length} application(s).`)}catch(e){$('progressWrap').hidden=true;say(`Assemblage impossible : ${e.message||e}`)}finally{operationBusy=false;render()}}
async function connectUsb(){if(operationBusy)return;if(!navigator.usb){say('WebUSB indisponible. Ouvrez cette application dans Chrome Android, sur une adresse HTTPS.');return}const api=window.NwlinkBrowserAPI;if(!api){say('Le moteur USB n’a pas chargé. Rechargez l’application.');return}operationBusy=true;render();$('usbStatus').className='usb-status';$('usbStatus').textContent='Connexion USB…';try{connectedCalculator=new api.CalculatorBulk();calculatorInfos=await connectedCalculator.singleConnectAndExtractInfos(true);$('usbStatus').className='usb-status ok';$('usbStatus').textContent='Calculatrice connectée — prête à recevoir';say('Calculatrice connectée. La liste complète sera écrite en un seul flash.')}catch(e){connectedCalculator=null;calculatorInfos=null;$('usbStatus').className='usb-status error';$('usbStatus').textContent='Connexion impossible';say(`USB : ${e.message||e}`)}finally{operationBusy=false;render()}}
async function installGroup(){if(operationBusy)return;if(!connectedCalculator||!calculatorInfos){say('Connectez d’abord la calculatrice avec le bouton ci-dessus.');return}operationBusy=true;render();setProgress(.02,'Préparation…');let prepTimer;try{const bundle=await makeBundle();const prepStarted=Date.now();setProgress(.08,`Assemblage 0/${apps.length}…`);prepTimer=setInterval(()=>{const seconds=Math.floor((Date.now()-prepStarted)/1000);setProgress(.08,seconds<60?`Assemblage ${Math.floor(seconds)} s · ${apps.length} applis`:`Assemblage ${Math.floor(seconds/60)} min · ${apps.length} applis`);},1000);await bundle.upload(calculatorInfos,p=>{if(p<.2){if(prepTimer){clearInterval(prepTimer);prepTimer=null}const done=Math.min(apps.length,Math.max(1,Math.ceil(p/.2*apps.length)));setProgress(.08+.92*p,`Assemblage ${done}/${apps.length}…`)}else if(p<.4){if(prepTimer){clearInterval(prepTimer);prepTimer=null}setProgress(.08+.92*p,`Préparation de la mémoire USB ${Math.round((p-.2)/.2*100)} %`)}else{if(prepTimer){clearInterval(prepTimer);prepTimer=null}setProgress(.08+.92*p,`Écriture USB ${Math.round((p-.4)/.6*100)} %`)}});if(prepTimer){clearInterval(prepTimer);prepTimer=null}setProgress(1,'Installation terminée');say(`Terminé : ${apps.length} application(s) installée(s) dans un seul flash.`)}catch(e){if(prepTimer)clearInterval(prepTimer);say(`Échec de l’installation : ${e.message||e}`)}finally{operationBusy=false;render()}}

for(const c of CATALOGUE){const o=document.createElement('option');o.value=c.id;o.textContent=c.name;$('catalogue').append(o)}
$('addCatalog').onclick=()=>addFromCatalog(CATALOGUE.find(c=>c.id===$('catalogue').value));$('pickNwa').onclick=()=>$('nwaFiles').click();$('nwaFiles').onchange=async e=>{for(const f of e.target.files)await addFile(f);e.target.value=''};
$('clearList').onclick=async()=>{if(!apps.length)return;if(!confirm('Vider toute la liste ?'))return;for(const a of apps){await dbDelete(a.nwaKey);if(a.dataKey)await dbDelete(a.dataKey)}apps=[];saveMeta();render();say('Liste vidée.')};$('exportPreset').onclick=exportPreset;$('importPreset').onclick=()=>$('presetFile').click();$('presetFile').onchange=e=>{if(e.target.files[0])importPreset(e.target.files[0]);e.target.value=''};
$('dryRun').onclick=dryRun;$('connectUsb').onclick=connectUsb;$('installGroup').onclick=installGroup;
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;$('installApp').hidden=false});$('installApp').onclick=async()=>{if(!deferredInstall)return;deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;$('installApp').hidden=true};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});restore();
